# Generated by Django 4.2.3 on 2023-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('ice cream', 'ice cream'), ('candy', 'candy'), ('chocolate bar', 'chocolate bar'), ('cake', 'cake'), ('other', 'other')], max_length=80)),
                ('price', models.PositiveIntegerField()),
                ('availability', models.BooleanField()),
                ('date_creation', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
