# Generated by Django 4.2.3 on 2023-07-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Products2',
        ),
    ]
